name: Build and Deploy Docker Image

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main

env:
  APP: api-qa2
  ENV: preview

jobs:
  print:
    runs-on: ubuntu-latest
    outputs:
      APP: ${{ steps.step1.outputs.APP }}
      ENV: ${{ steps.step1.outputs.ENV }}
    steps:
      - name: Print inputs passed to the reusable workflow
        id: step1
        run: |
          echo "APP: $APP" && echo "APP=$APP" >> $GITHUB_OUTPUT
          echo "ENV: $ENV" && echo "ENV=$ENV" >> $GITHUB_OUTPUT

  execute-tests:
    uses: remidqa/use-guthubactions/.github/workflows/main.yml@main
    needs:
      - print
    with:
      APP: ${{ needs.print.outputs.APP }}
      ENV: ${{ needs.print.outputs.ENV }}
