name: Build and Deploy Docker Image
env:
  APP: api-qa2
  ENV: preview

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main

jobs:
  execute-tests:
    uses: remidqa/use-guthubactions/.github/workflows/main.yml@main
    with:
      APP: ${{ env.APP }}
      ENV: ${{ env.ENV }}
