name: Build and Deploy Docker Image

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main

env:
  APP: api-qa
  ENV: preview

jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      APP: ${{ steps.getEnvVars.outputs.APP }}
      ENV: ${{ steps.getEnvVars.outputs.ENV }}
    steps:
      - name: Print inputs passed to the reusable workflow
        id: getEnvVars
        run: |
          echo "APP: $APP" && echo "APP=$APP" >> $GITHUB_OUTPUT
          echo "ENV: $ENV" && echo "ENV=$ENV" >> $GITHUB_OUTPUT

  build:
    needs:
      - vars
    uses: remidqa/use-guthubactions/.github/workflows/docker-build-push.yml@main
    with:
      APP: ${{ needs.vars.outputs.APP }}
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    needs:
      - build
    uses: remidqa/use-guthubactions/.github/workflows/pull-deploy.yml@main
    with:
      APP: ${{ needs.vars.outputs.APP }}
    secrets:
      SSH_SERVER: ${{ secrets.SSH_SERVER }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

  execute-tests:
    uses: remidqa/use-guthubactions/.github/workflows/main.yml@main
    needs:
      - vars
      - build
    with:
      APP: ${{ needs.vars.outputs.APP }}
      ENV: ${{ needs.vars.outputs.ENV }}
