name: Build and Deploy Docker Image

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main

jobs:
  execute-tests:
    uses: remidqa/use-guthubactions/.github/workflows/main.yml@main
    with:
      APP: api-qa2
      ENV: preview
