name: Build and Deploy Docker Image

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: remidqa/use-guthubactions@main
        with:
          APP: api-qa2
          ENV: preview
